"""empty message

Revision ID: 25db5b662c75
Revises: 
Create Date: 2022-06-07 17:06:25.819557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25db5b662c75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('product_description', sa.String(length=191), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
