"""empty message

Revision ID: 550942151b88
Revises: 2497be69a210
Create Date: 2022-06-07 17:27:00.879351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550942151b88'
down_revision = '2497be69a210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer__product',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer__product')
    # ### end Alembic commands ###
